name: CI CD and deploy to Tomcat
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build the project
        run: |
          mvn package -DskipTests=true
          mvn war:war
      - name: Update application.properties
        run: |
          sed -i -e 's|${DB_URL}|${{ secrets.DB_URL }}|g' target/Kino_CMS-Yura_Dmytriv/WEB-INF/classes/application.properties
          sed -i -e 's|${DB_LOGIN}|${{ secrets.DB_LOGIN }}|g' target/Kino_CMS-Yura_Dmytriv/WEB-INF/classes/application.properties
          sed -i -e 's|${DB_PASSWORD}|${{ secrets.DB_PASSWORD }}|g' target/Kino_CMS-Yura_Dmytriv/WEB-INF/classes/application.properties
      - name: Copy folder
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/Kino_CMS-Yura_Dmytriv
          remote: tomcat/webapps/Kino_CMS-Yura_Dmytriv
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Copy file
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/Kino_CMS-Yura_Dmytriv.war
          remote: tomcat/webapps/Kino_CMS-Yura_Dmytriv.war
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}